# Generated by Django 5.1.5 on 2025-09-11 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='retailapp.productsubcategory'),
            preserve_default=False,
        ),
    ]
