# Generated by Django 5.1.5 on 2025-03-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
