# Generated by Django 5.1.5 on 2025-04-07 11:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0004_alter_customer_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/djedeaw0l/image/upload/v1744019579/customerprofile/w7kmmmmsibzmn5lfu1qx.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
