# Generated by Django 5.1.5 on 2025-09-09 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0005_alter_customer_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_list',
            name='prize_range',
        ),
        migrations.RemoveField(
            model_name='product_list',
            name='product_category',
        ),
        migrations.AddField(
            model_name='product_list',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='retailapp.product_category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_list',
            name='price_range',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
